---
kind: pipeline
name: Nexus WhyRed OldCam
steps:
  - name: llvm-clang oldcam
    image: archlinux:base-devel
    environment: 
      token: 
        from_secret: token
      chat_id: 
        from_secret: chat_id
    commands:
      - curl -LO "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" && bsdtar -C / -xvf "glibc-linux4-2.33-4-x86_64.pkg.tar.zst"
      - pacman -Sy && pacman -S git curl bc inetutils python2 zip jdk-openjdk --noconfirm
      - bash .droneci/build.sh --oldcam

---
kind: pipeline
name: Nexus WhyRed NewCam
steps:
  - name: llvm-clang newcam
    image: archlinux:base-devel
    environment: 
      token: 
        from_secret: token
      chat_id: 
        from_secret: chat_id
    commands:
      - curl -LO "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" && bsdtar -C / -xvf "glibc-linux4-2.33-4-x86_64.pkg.tar.zst"
      - pacman -Sy && pacman -S git bc inetutils python2 zip jdk-openjdk --noconfirm
      - bash .droneci/build.sh --newcam
